name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out StateMachine
on: [push]
jobs: 
  testing: 
    runs-on: ubuntu-latest

    steps:
      - run: echo "Starting the Test for the Statemachine"
