name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x' # Use the version you need

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build

    - name: Run tests
      run: dotnet test
